require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "vendor/bundle/**/*"

Layout/LineLength:
  Max: 120
  Exclude:
    - app/helpers/application_helper.rb

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 12

Minitest/MultipleAssertions:
  Max: 10

Naming/BlockForwarding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
  Exclude:
    - Gemfile

Style/WordArray:
  EnforcedStyle: brackets
