require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

AllCops:
  TargetRubyVersion: 3.2
  # Auto-enable all new pending cops between releases
  NewCops: enable
  # Mostly disabling the majority of the Rails-generated configuration files
  # We should try to at least manually maintain the frozen string litteral
  # magic comment rule, if possible
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'app/javascript/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Exclude:
    - 'app/helpers/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Rails/HelperInstanceVariable:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/registrations_controller.rb'
    - 'app/controllers/sessions_controller.rb'

Rails/I18nLocaleTexts:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GlobalStdStream:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
